spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/hikmetqulami/config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


  #          search-locations: "classpath:/config"
  rabbitmq:
    host: "rabbit"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
encrypt:
  key: "NXC78ZGEC84AX13GFBLSSYBQAZDU4361NMDQPMFK9V5GB4DIGA"